[package]
name = "bio"
version = "0.21.1-alpha.0"
authors = ["Johannes Köster <johannes.koester@tu-dortmund.de>"]
description = "A bioinformatics library for Rust. This library provides implementations of many algorithms and data structures that are useful for bioinformatics, but also in other fields."
homepage = "https://rust-bio.github.io"
repository = "https://github.com/rust-bio/rust-bio"
documentation = "https://docs.rs/bio"
readme = "README.md"
license = "MIT"

[features]
avx-accel = ["bytecount/avx-accel"]
simd-accel = ["bytecount/simd-accel"]
flame_it = ["flame", "flamer"]

[dependencies]
bytecount = "0.3.1"
csv = "1.0.0-beta.5"
num-traits = "0.1"
num-integer = "0.1"
itertools = "0.6"
itertools-num = "0.1"
bv = { version = "0.7", features = ["serde"] }
bit-set = "0.4"
ndarray= "0.9"
lazy_static = "0.2"
serde = "1.0"
serde_derive = "1.0"
approx = "0.1"
custom_derive = "0.1"
newtype_derive = "0.1"
ordered-float = "0.5"
quick-error = "1.2"
regex = "0.2"
multimap = "0.4"
fxhash = "0.2"
flame = { git = "https://github.com/TyOverby/flame.git", branch = "master", optional = true }
flamer = { version = "^0.2.3", optional = true }

[dependencies.vec_map]
version = "0.8"
features = ["eders"]

[package.metadata.release]
pre-release-commit-message = "release version {{version}}"
tag-message = "Version {{version}} of Rust-Bio."
